spring:
  jpa:
    open-in-view: true
    #    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    #        format_sql: true
#    defer-datasource-initialization: true # Wait for table creation.
#  sql.init.mode: always                   # initialize data
