prepare:
  utf8-conversion-extensions:
    - java
    - txt
    - properties
    - xml
    - css
    - csv
    - MF
    - html
    - script
    - js
    - sql
    - sh
    - htm
    - jsp

  ignored-jar-prefix:
    - jconn
    - tibero
    - log4jdbc
    - modelmapper
    - stax2
    - geronimo
    - jsr305
    - jmespath
    - mybatis
    - woodstox
    - config
    - google
    - fontbox
    - rhino
    - guava
    - stax
    - classmate
    - perfmark
    - accessors
    - jul
    - yaml
    - mbassador
    - jboss
    - icu4j
    - eddsa
    - webjars
    - asn
    - tomcat
    - hibernate
    - caffeine
    - api
    - batik
    - logback
    - ojdbc10
    - auto
    - byte
    - jsch
    - smbj
#    - commons
    - httpcore
    - winrm4j
    - error_prone_annotations
    - txw2
    - listenablefuture
    - hamcrest
    - jaxws
    - wsdl4j
    - swagger
    - juniversalchardet
    - proto
    - jjwt
    - mariadb
    - failureaccess
    - jcifs
    - sshj
    - slf4j
    - xmlbeans
    - log
    - httpclient
    - istack
    - opentracing
    - common
    - joda
    - mysql
    - opencsv
    - overthere
    - jakarta.validation
    - pdfbox
    - mssql
    - dom4j
    - opencensus
    - threetenbp
    - gax
    - xml
    - HikariCP
    - grpc
    - jPowerShell
    - xalan
    - annotations
    - antlr
    - springdoc
    - serializer
    - log4j
    - snakeyaml
    - spring
    - orai18n
    - truezip
    - cfr
    - jackson
    - jaxen
    - curvesapi
    - xmlunit
    - json
    - xmlsec
    - protobuf
    - expiringmap
    - jakarta.xml.soap
    - animal
    - jacorb
    - checker
    - jakarta.xml.bind
    - jakarta.annotation
    - jcl
    - javax.activation
    - jakarta.activation
    - classgraph
    - asm
    - javax.annotation
    - xmlgraphics
    - poi
    - neethi
    - conscrypt
    - jakarta.persistence
    - tika
    - saaj
    - jakarta.transaction
    - evo
    - javax.xml.soap
    - cxf
    - junit
    - aws
    - aspectjweaver
    - graphics2d
    - jandex
    - gson
    - jzlib
    - xmlschema
    - j2objc
    - scannit
    - httpasyncclient
    - ion
    - SparseBitSet
    - javassist
    - jaxb
    - bcprov
    - bcpkix
