package io.playce.migrator.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;


@Getter
@AllArgsConstructor
public enum ErrorCode {
//  code 체계
//  6자리
//  2 + 3 + 1
//  최조 2자리: Playce Migrator 약자.
//  중간 3자리: 일련번호
//  끝  1자리: ErrorType 정의 됨(새로운 타입은 여기에 정의해야함)
//      H : http
//      R : resource
//      F : file
//      D : database
//      A : auth
//      S : Scm

    // http
    PM101H(BAD_REQUEST),
    PM102H(UNAUTHORIZED),
    PM103H(FORBIDDEN),
    PM104H(METHOD_NOT_ALLOWED),
    PM105H(UNSUPPORTED_MEDIA_TYPE),
    PM106H(INTERNAL_SERVER_ERROR),
    PM107H(BAD_REQUEST),

    // resource
    PM201R(NOT_FOUND),
    PM202R(BAD_REQUEST),
    PM271R(INTERNAL_SERVER_ERROR),

    //file
    PM301F(BAD_REQUEST),
    PM302F(INTERNAL_SERVER_ERROR),
    PM303F(INTERNAL_SERVER_ERROR),
    PM304F(INTERNAL_SERVER_ERROR),
    PM305F(INTERNAL_SERVER_ERROR),
    PM306F(INTERNAL_SERVER_ERROR),
    PM307F(INTERNAL_SERVER_ERROR),
    PM308F(INTERNAL_SERVER_ERROR),
    PM309F(INTERNAL_SERVER_ERROR),
    PM310F(INTERNAL_SERVER_ERROR),
    PM371F(INTERNAL_SERVER_ERROR),
    PM372F(INTERNAL_SERVER_ERROR),
    PM373F(INTERNAL_SERVER_ERROR),
    PM374F(INTERNAL_SERVER_ERROR),
    PM375F(INTERNAL_SERVER_ERROR),
    PM376F(INTERNAL_SERVER_ERROR),
    PM377F(INTERNAL_SERVER_ERROR),
    PM378F(INTERNAL_SERVER_ERROR),

    //db
    PM401D(INTERNAL_SERVER_ERROR),
    PM402(INTERNAL_SERVER_ERROR),

    //auth
    PM501A(BAD_REQUEST),
    PM502A(BAD_REQUEST),
    PM503A(UNAUTHORIZED),
    PM504A(BAD_REQUEST),
    PM505A(BAD_REQUEST),
    PM506A(UNAUTHORIZED),
    PM507A(BAD_REQUEST),
    PM508A(UNAUTHORIZED),
    PM509A(UNAUTHORIZED),
    PM510A(UNAUTHORIZED),
    PM511A(UNAUTHORIZED),
    PM512A(UNAUTHORIZED),
    PM513A(UNAUTHORIZED),
    PM514A(UNAUTHORIZED),
    PM515A(BAD_REQUEST),
    PM517A(UNAUTHORIZED),
    PM516A(UNAUTHORIZED),


    // load private key
    PM601J(INTERNAL_SERVER_ERROR),
    PM701T(INTERNAL_SERVER_ERROR),
    PM702T(BAD_REQUEST),
    PM703T(BAD_REQUEST),
    PM704T(BAD_REQUEST),
    PM705T(INTERNAL_SERVER_ERROR),
    PM706T(INTERNAL_SERVER_ERROR),
    PM707T(INTERNAL_SERVER_ERROR),

    PM801S(BAD_REQUEST),
    PM802S(BAD_REQUEST),
    PM803S(INTERNAL_SERVER_ERROR),
    PM804S(BAD_REQUEST),
    PM805S(BAD_REQUEST),
    PM806S(BAD_REQUEST),

    // subscription,
    PM901SUB(PAYMENT_REQUIRED),
    PM902SUB(PAYMENT_REQUIRED),
    PM903SUB(PAYMENT_REQUIRED),
    PM904SUB(PAYMENT_REQUIRED),
    PM905SUB(PAYMENT_REQUIRED),
    ;

    private final HttpStatus httpStatus;
}
